name: Pull Request
about: Create a pull request to contribute to the project
title: ''
labels: ''
assignees: ''
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the changes being made.
    validations:
      required: true
  - type: textarea
    id: related-issue
    attributes:
      label: Related Issue
      description: Please link to the issue that this pull request addresses. If there is no related issue, please create one.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have read the [CONTRIBUTING.md](CONTRIBUTING.md) file.
          required: true
        - label: I have added tests to cover my changes.
          required: false
        - label: All new and existing tests passed.
          required: false
        - label: I have updated the documentation to reflect my changes.
          required: false
