name: Documentation
description: Request to improve or update MTG Rulings Bot documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Please provide details about what documentation needs to be updated or added.
  - type: textarea
    id: improvement
    attributes:
      label: What documentation improvement or update would you like to see?
      description: "Example: The MTG Rulings Bot docs are missing information about specific card interactions or command usage."
      placeholder: Please describe the documentation change you'd like to see...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand the documentation need.
      placeholder: Additional context, use cases, or examples that would help us understand...
    validations:
      required: true
  - type: input
    id: existing-docs
    attributes:
      label: Does the documentation page already exist? Please link to it.
      description: "If you're suggesting an update to existing documentation, please provide the link."
      placeholder: "Example: https://github.com/MohnishKalia/MTGRulingsBot/blob/main/README.md"
    validations:
      required: false
  - type: dropdown
    id: doc-category
    attributes:
      label: Documentation Category
      description: What type of documentation is this related to?
      options:
        - README/Getting Started
        - API Documentation
        - Command Reference
        - MTG Rules/Card Interactions
        - Installation/Setup Guide
        - Contributing Guidelines
        - Code Comments/Inline Documentation
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation update?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for users
        - Critical - Blocking users
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm before submitting your documentation request.
      options:
        - label: I have searched existing issues to ensure this documentation request hasn't been made before
          required: true
        - label: I have provided a clear description of the documentation improvement needed
          required: true
