blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/MohnishKalia/MTGRulingsBot/discussions
    about: For general questions and community discussions about the MTG Rulings Bot
  - name: GitHub Security
    url: https://github.com/MohnishKalia/MTGRulingsBot/security/policy
    about: Please report security vulnerabilities here
